name: CI
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: pwsh
jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    services:
      ibm-mq:
        image: icr.io/ibm-messaging/mq:latest
        ports:
          - 1414:1414
          - 9443:9443
        env:
          LICENSE: accept
          MQ_QMGR_NAME: QM1
          MQ_ADMIN_PASSWORD: passw0rd
        options: >-
          --health-cmd "dspmq"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 30s
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: 10.0.x
      - name: Build
        run: dotnet build src/NServiceBus.Transport.IbmMq.slnx --configuration Release
      - name: Run tests
        run: dotnet test src/NServiceBus.Transport.IbmMq.slnx --configuration Release --no-build
