name: CI
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:
    inputs:
      run_perf_tests:
        description: Run performance tests
        type: boolean
        default: false
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: pwsh
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows
          - os: ubuntu-latest
            name: Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Setup WSL
        uses: Particular/setup-wsl-action@v1.2.0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6.0.0
        with:
          global-json-file: global.json
      - name: Setup IBM MQ
        uses: Particular/setup-ibmmq-action@75b6087748fcdaef474574ca1fbe2b440141f07f
        with:
          connection-string-name: IBMMQ_CONNECTIONSTRING
          init-script: .github/workflows/setup-leastpriv-tests.sh
      - name: Build
        run: dotnet build src --configuration Release
      - name: Upload packages
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NuGet packages
          path: nugets/
          retention-days: 7
      - name: Run tests
        uses: Particular/run-tests-action@v1.7.0
